stolostron/multicloud-operators-application

.travis.yml
sonar-project.properties

Signed-off-by: Xiangjing Li <xilica.ibm.com@Xiangjings-MacBook-Pro.local>

enable sonarCloud

---

.travis.yml
Makefile

open-cluster-management/backlog#1060
Fixing above,

application repo tagging image for community operator

---

.travis.yml
utils/kubernetes.go

Signed-off-by: Xiangjing Li <xilica.ibm.com@Xiangjings-MacBook-Pro.local>
https://github.com/open-cluster-management/backlog/issues/975
https://github.com/open-cluster-management/backlog/issues/1085

security scan fixes

---

utils/explore.go

update license copyright

---

utils/kubernetes.go

security fix

---

.gitignore
deploy/crds/standalone/apps.open-cluster-management.io_deployable_crd.yaml
deploy/crds/standalone/apps.open-cluster-management.io_subscriptions_crd.yaml
go.mod
pkg/apis/addtoscheme_apps_v1beta1.go
pkg/controller/application/application_controller_suite_test.go
pkg/controller/application/application_controller_test.go

add reconcile unit test

---

README.md
sonar-project.properties

cicd related fixes

---

go.mod
go.sum
utils/explore_test.go
utils/kubernetes_suite_test.go
utils/kubernetes_test.go

added more tests

---

Makefile

remove patch check

---

cmd/manager/exec/manager.go
webhook/certificate.go
webhook/webhook_test.go

create new path for registering application webhook

---

build/Dockerfile

update ubi to latest

---

CONTRIBUTING.md
DCO
README.md
deploy/operator.yaml
deploy/role.yaml
deploy/role_binding.yaml
deploy/service_account.yaml
docs/deployment.md
docs/development.md

update community doc

---

examples/nginx-app.yaml

apply new working helm repo

---

docs/development.md

cherry-pick from https://github.com/open-cluster-management/multicloud-operators-application/pull/68
The other PR is going to master and this one will go to main branch instead.

small changes: open-cluster-management/backlog#7113

---

Makefile.prow

fixes for prow

---

build/run-code-lint.sh
cmd/manager/exec/manager.go
common/config/.golangci.yml

fix lint, skip magic number check

---

Makefile.prow
build/run-code-lint.sh

The prow build is having difficulty with the lint target in the original Makefile lint target. I pulled the pieces that its running into the dedicated `Makefile.prow` hopefully this will resolve the issue.

fix lint for prow

---

README.md

test prow from fork

---

cmd/manager/exec/options.go
docs/development.md

https://github.com/open-cluster-management/backlog/issues/10942

fix loading crd file name

---

build/Dockerfile.prow
go.mod

use go 1.6

---

pkg/controller/application/hub.go

https://github.com/open-cluster-management/backlog/issues/12201
Signed-off-by: Philip Wu phwu@redhat.com

Add app label to subscription resources

---

pkg/controller/application/hub.go

https://github.com/open-cluster-management/backlog/issues/12201
Signed-off-by: Philip Wu <phwu@redhat.com>

Change from app label to part-of label

---

deploy/crds/app.k8s.io_applications_crd_v1.yaml
deploy/crds/standalone/apps.open-cluster-management.io_deployable_crd.yaml
deploy/crds/standalone/apps.open-cluster-management.io_subscriptions_crd.yaml

https://github.com/open-cluster-management/backlog/issues/8702
Signed-off-by: Philip Wu <phwu@redhat.com>

Change spec to required

---

README.md

No op change to test new CICD integration changes.

commit to test cicd

---

go.mod
go.sum

Signed-off-by: Roke Jung <roke@redhat.com>

new subscription module

---

build/Dockerfile.prow
build/setup-tests.sh
go.mod

https://github.com/open-cluster-management/backlog/issues/15572

upgrade to go v1.17

---

README.md

Trigger a prow job

---

README.md

Signed-off-by: Mike Ng <ming@redhat.com
trying again since last PR the fast-forward mysteriously failed.

trigger prow cicd

---

webhook/wireupwebhook.go

https://github.com/stolostron/backlog/issues/20555
follow the fix in channel repo to ignore those unidentified error
https://github.com/stolostron/backlog/issues/20555#issuecomment-1068591970

loose validating webhook failure policy

---

utils/application_test.go
utils/eventlog.go
utils/kubernetes_test.go

Signed-off-by: Jonathan Marcantonio <jmarcant@redhat.com>

Add unit tests to increase coverage

---

pkg/controller/application/application_controller_test.go
webhook/certificate_test.go

Signed-off-by: Jonathan Marcantonio <jmarcant@redhat.com>

Add unit tests to increase code coverage

---

OWNERS
pkg/controller/application/hub.go
utils/kubernetes_suite_test.go
utils/utils_test.go

Add some unit tests

---

utils/application_test.go

Add TestPredicate

---

pkg/controller/application/application_controller_test.go
utils/application_test.go

Add more coverage

---

utils/application_test.go

increase util test coverage

---

utils/application_test.go

increase test coverage

---

pkg/controller/application/application_controller_test.go

Add more tests

---

webhook/webhook_suite_test.go
webhook/webhook_test.go

refactor webhook unit tests

---

pkg/controller/application/application_controller_test.go

add unit test to application controller

---

build/Dockerfile.prow
go.mod

https://github.com/stolostron/backlog/issues/26086

Release 2.5 - Upgrade go version

---

build/Dockerfile.prow
common/config/.golangci.yml
go.mod

https://github.com/stolostron/backlog/issues/26028

Upgrade go version to 1.19

---

cmd/manager/exec/manager.go
common/scripts/gobuild.sh
pkg/apis/addtoscheme_apps_v1beta1.go

Addresses CVE-2023-3089
Will cherry-pick to release-2.8.

Update build parameters

---

go.mod
go.sum

https://issues.redhat.com/browse/ACM-6477

Upgrade goproxy to address CVE-2023-37788

---

.tekton/multicluster-operators-application-acm-214-pull-request.yaml
.tekton/multicluster-operators-application-acm-214-push.yaml
build/Dockerfile
build/Dockerfile.prow
build/Dockerfile.rhtap

Sync main with release-2.14 branch

Sync main with release-2.14 branch

---

.tekton/multicluster-operators-application-acm-214-pull-request.yaml
.tekton/multicluster-operators-application-acm-214-push.yaml
build/Dockerfile.rhtap
rpms.in.yaml
rpms.lock.yaml

https://issues.redhat.com/browse/ACM-20611
Enable hermetic build

Enable hermetic build

---

.tekton/multicluster-operators-application-acm-212-pull-request.yaml
.tekton/multicluster-operators-application-acm-212-push.yaml
build/Dockerfile.rhtap
rpms.in.yaml
rpms.lock.yaml

https://issues.redhat.com/browse/ACM-23297

move to konflux common pipeline
